import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useState } from "react";
import Flexbox from "./HTML-css/flexbox";
import Assignment1 from "./HTML-css/Assignment1";
import AssetDetailPage from "./HTML-css/AssetDetailPage";
import { Provider } from "react-redux";
import store from "@/data/redux/Store";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [count, setCount] = useState<number>(0);
  return (
    <Provider store={store}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Flexbox /> */}
      {/* <Assignment1 /> */}
      <AssetDetailPage />
    </Provider>
  );
}
